// Auto-generated image mappings for Sri Kanya Restaurant
// Generated from Cloudinary collection: https://collection.cloudinary.com/dklpiguqs/a7929dc14ac74d52a008e57053c387a6

export const foodImageMappings: { [key: string]: string } = {
  '65_paneer_mushroom_ralhgb': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/65_paneer_mushroom_ralhgb',
  'accessories-bag': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/ecommerce/accessories-bag',
  'architecture-signs': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/landscapes/architecture-signs',
  'balloons': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/balloons',
  'beach-boat': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/landscapes/beach-boat',
  'bicycle': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/people/bicycle',
  'bike': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/bike',
  'boneless_curry_uc9dcs': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/boneless_curry_uc9dcs',
  'boy-snow-hoodie': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/people/boy-snow-hoodie',
  'breakfast': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/breakfast',
  'car-interior-design': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/ecommerce/car-interior-design',
  'chair': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/chair',
  'chair-and-coffee-table': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/chair-and-coffee-table',
  'chicken_555_kuqke1': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_555_kuqke1',
  'chicken_biryani_hpabwk': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_biryani_hpabwk',
  'chicken_curry_yx4fkd': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_curry_yx4fkd',
  'chicken_dum_biryani_half_tk7c4i': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_dum_biryani_half_tk7c4i',
  'chicken_fried_rice_hm2pc4': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_fried_rice_hm2pc4',
  'chicken_fry_ulixuq': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_fry_ulixuq',
  'chicken_mughlai_vsmcmq': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_mughlai_vsmcmq',
  'chicken_noodles_ee5phk': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_noodles_ee5phk',
  'chicken_schezwan_noodles_gkgcuo': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_schezwan_noodles_gkgcuo',
  'chilly_chicken_owi5su': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chilly_chicken_owi5su',
  'chilly_paneer_mushroom_iicqqh': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chilly_paneer_mushroom_iicqqh',
  'cld-sample': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/cld-sample',
  'cld-sample-2': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/cld-sample-2',
  'cld-sample-3': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/cld-sample-3',
  'cld-sample-4': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/cld-sample-4',
  'cld-sample-5': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/cld-sample-5',
  'cloudinary-group': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/cloudinary-group',
  'coffee': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/coffee',
  'cup-on-a-table': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/cup-on-a-table',
  'dessert-on-a-plate': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/dessert-on-a-plate',
  'dragon_chicken_ujeume': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/dragon_chicken_ujeume',
  'egg_bhurji_ghzuch': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/egg_bhurji_ghzuch',
  'egg_fried_rice_byzwmj': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/egg_fried_rice_byzwmj',
  'egg_keema_soseqb': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/egg_keema_soseqb',
  'egg_noodles_kdmwmd': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/egg_noodles_kdmwmd',
  'fish_fry_qiju4o': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/fish_fry_qiju4o',
  'imagecon-group': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/imagecon-group',
  'jazz': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/people/jazz',
  'joint_biryani_ovrbc6': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/joint_biryani_ovrbc6',
  'kadai_chicken_wishxq': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/kadai_chicken_wishxq',
  'kaju_biryani_hmsekh': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/kaju_biryani_hmsekh',
  'kaju_chicken_balls_empxbq': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/kaju_chicken_balls_empxbq',
  'kaju_chicken_ebyauf': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/kaju_chicken_ebyauf',
  'kaju_fry_davndh': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/kaju_fry_davndh',
  'kaju_masala_yti9z5': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/kaju_masala_yti9z5',
  'kaju_tomato_jbm1vj': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/kaju_tomato_jbm1vj',
  'kitten-playing': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/animals/kitten-playing',
  'landscape-panorama': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/landscapes/landscape-panorama',
  'leather-bag-gray': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/ecommerce/leather-bag-gray',
  'logo': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/logo',
  'lolipop_biryani_z4tush': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/lolipop_biryani_z4tush',
  'lolipop_chicken_snaglx': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/lolipop_chicken_snaglx',
  'look-up': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/look-up',
  'loose_prawns_chilli_kp1ngl': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/loose_prawns_chilli_kp1ngl',
  'machurian_paneer_z6olpc': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/machurian_paneer_z6olpc',
  'main-sample': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/main-sample',
  'man-on-a-escalator': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/man-on-a-escalator',
  'man-on-a-street': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/man-on-a-street',
  'man-portrait': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/man-portrait',
  'manchurian_chicken_wbtgvn': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/manchurian_chicken_wbtgvn',
  'methi_chaman_e2mnf1': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/methi_chaman_e2mnf1',
  'methi_chicken_xvsxjc': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/methi_chicken_xvsxjc',
  'mix_biryani_loofey': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mix_biryani_loofey',
  'mix_fried_rice_nonveg_fa8vrh': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mix_fried_rice_nonveg_fa8vrh',
  'mix_fried_rice_veg_dxe7es': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mix_fried_rice_veg_dxe7es',
  'mixed_veg_biryani_jdlmp7': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mixed_veg_biryani_jdlmp7',
  'mughlai_biryani_pjot1d': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mughlai_biryani_pjot1d',
  'mushroom_curry_vyzob0': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mushroom_curry_vyzob0',
  'mushroom_fried_rice_ri42pq': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mushroom_fried_rice_ri42pq',
  'mutton_biryani_s37yud': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mutton_biryani_s37yud',
  'mutton_curry_wp7sq9': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mutton_curry_wp7sq9',
  'mutton_fried_rice_e4ybfb': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mutton_fried_rice_e4ybfb',
  'mutton_fry_zzktfa': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mutton_fry_zzktfa',
  'nature-mountains': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/landscapes/nature-mountains',
  'outdoor-woman': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/outdoor-woman',
  'palak_chicken_fgjmeh': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/palak_chicken_fgjmeh',
  'paneer_butter_masala_htawqb': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/paneer_butter_masala_htawqb',
  'paneer_fried_rice_njjdbf': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/paneer_fried_rice_njjdbf',
  'prawn_curry_lheqay': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/prawn_curry_lheqay',
  'prawns_biryani_v6hybp': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/prawns_biryani_v6hybp',
  'prawns_fried_rice_oxzsmr': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/prawns_fried_rice_oxzsmr',
  'pulka_dddf21': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/pulka_dddf21',
  'schezwan_fried_rice_pz7wpr': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/schezwan_fried_rice_pz7wpr',
  'shoe': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/shoe',
  'smile': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/smile',
  'sp_chicken_biryani_olg6y4': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/sp_chicken_biryani_olg6y4',
  'sp_nonveg_fried_rice_vbizyg': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/sp_nonveg_fried_rice_vbizyg',
  'sp_veg_fried_rice_hdhvcp': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/sp_veg_fried_rice_hdhvcp',
  'spices': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/food/spices',
  'three-dogs': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/animals/three-dogs',
  'two-ladies': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/two-ladies',
  'upscale-face-1': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/upscale-face-1',
  'veg_fried_rice_ufpjbt': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/veg_fried_rice_ufpjbt',
  'veg_manchurian_rioeyc': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/veg_manchurian_rioeyc',
  'veg_noodles_asuy1h': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/veg_noodles_asuy1h',
  'wings_fry_rvxgpq': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/wings_fry_rvxgpq',
  'woman-on-a-football-field': 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/samples/woman-on-a-football-field',
};

// Function to get the appropriate image for a menu item
export function getFoodImage(itemId: string): string {
  return foodImageMappings[itemId] || 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_biryani_hpabwk';
}

// Function to get fallback image based on category
export function getFallbackImage(category: string): string {
  const categoryImages: { [key: string]: string } = {
    biryanis: 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_biryani_hpabwk',
    vegCurries: 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/mushroom_curry_vyzob0',
    nonVegCurries: 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_biryani_hpabwk',
    friedRiceNoodles: 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/paneer_fried_rice_njjdbf',
    breadsRoti: 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_biryani_hpabwk',
  };

  return categoryImages[category] || 'https://res.cloudinary.com/dklpiguqs/image/upload/w_400,h_300,c_fill,f_auto,q_auto/chicken_biryani_hpabwk';
}
